auth:
  secret: ${AUTH_SECRET:4988c72e251839b3ea1f18bed3e85342f1a09e98}

spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://benthos:oXEeYY5XqQS1PlFX@cluster0.coq8i.mongodb.net/db_benthos?retryWrites=true&w=majority}
